grid_visualization:
  # Options: "hash", "q-base", "neighbor-similarity-hash", "neighbor-similarity-q-base"
  mode: "neighbor-similarity-hash"
  #Options: "light", "dark", "chaotic", "vibrant"
  theme: "light"
  base_node_setting: 40000 # Increase to make all nodes bigger
  base_line_setting: 50 # Increase to make all lines thicker

# Settings for standard single runs (main.py)
test_simulation_defaults:
  width: 20
  height: 20
  features: 3
  traits: 10
  seed: 42
  max_steps: 200000 # High limit; we rely on the frozen check
  plot_interval: 10000

# Parameters for the large-scale experiment
experiment:
  master_seed: 42
  M_realizations: 10
  max_steps: 200000 # High limit; we rely on the frozen check

  # Every combination of these will be tested (Cartesian Product)
  sweep:
    F: [3, 8]
    q: [2, 5, 8, 10, 12, 13, 14, 15, 18, 20, 25, 30]
    width: [20, 40, 50]
