simulation:
  width: 30
  height: 30
  features: 5 # F: Number of cultural categories
  traits: 10 # q: Possible variations per category
  max_steps: 200000
  seed: 42
  plot_interval: 50000

visualization:
  # Options: "hash", "q-base", "neighbor-similarity-hash", "neighbor-similarity-q-base"
  mode: "neighbor-similarity-hash"
  #Options: "light", "dark", "chaotic", "vibrant"
  theme: "light"
  base_node_setting: 40000 # Increase to make all nodes bigger
  base_line_setting: 50 # Increase to make all lines thicker
